### ISSUE TITLE
grant write permission to others

### ISSUE THREAD

**Issue by jjangga0214** [cowlicks/privacypossum#176]
Hi @cowlicks! 
Thank you for this convenient extension.

However, it seems this project is not actively managed.
There are many(70) open issues, and the last commit was a few months ago.

If you don't have enough time to handle, 
why don't you consider giving write permission to other people?

Or having difficulty finding a suitable candidate? 
Then what about letting people know that first? (e.g. write that on README.md)

Thanks.

**Comment by FrostKnight** [comment]
I hate to say this, and I mean really hate to say this, but if he doesn't respond at some point within this year it may need to be forked. D:

**Comment by jjangga0214** [comment]
@FrostKnight  Yeah, I agree. That would be the only way. Curious who's gonna fork and reflect waiting PRs and issues as well as add some useful features if desired.

**Comment by FrostKnight** [comment]
Well... someone needs to do it soon probably unless cowlicks wakes up and says he will start working on it again.  :0

I even emailed him, I hope he will reply at some point.

**Comment by cowlicks** [comment]
Hi @FrostKnight @jjangga0214 thanks for your interest. Sorry for not being more active. I've been working full time, and haven't had the time to spend here.

I'd be happy to give write permissions to others *eventually* when they've built up trust by contributing via pull requests.

About the issue number: indeed most are valid, but there are a lot of low quality issues because I included a link to GitHub in the extension as a way to report bugs. If anyone would like to volunteer to help me triage issues, that would be awesome, and is a good task for beginners. Help creating a better bug report system is also welcome.

I plan on making a release this weekend!

Thanks,

**Comment by FrostKnight** [comment]
@cowlicks 

Yeah... I wasn't suggesting you give me write permission, just people who have been  making commits who you trust.

It is good to hear you will be making a release this weekend, because I would hate to see this die.
