### ISSUE TITLE
Error on citi website after logging on

### ISSUE THREAD

**Issue by ramenchef** [cowlicks/privacypossum#26]
I am getting many errors after logging into my banking account on citi. Even using the disable button doesn't fix the issue. Only disabling the entire extension in chrome fixes the issue. This is on version 2018.5.7 on chrome Version 66.0.3359.139 (Official Build) (64-bit)

Uncaught SyntaxError: Invalid regular expression: /)$/: Unmatched ')'
    at String.match (<anonymous>)
    at String.endsWith (jfp.combined.min.js:1)
    at getUrlFromStackLine (fingercounting.js:41)
    at Counter.getScriptLocation (fingercounting.js:33)
    at Navigator.get (fingercounting.js:197)
    at jfp.combined.min.js:68
    at jfp.combined.min.js:70

Uncaught TypeError: CJW.jfp.widget.Overlay is not a constructor
    at f (Home.do?JFP_TOKEN=MDC5XNIC:10714)
    at Home.do?JFP_TOKEN=MDC5XNIC:10736
    at Home.do?JFP_TOKEN=MDC5XNIC:10737

**Comment by cowlicks** [comment]
@ramenchef thank you for the report. To fix the issue with disabling I'm working on #35.

I'm also still working on figuring out the edge cases in the fingerprinting script that are causing this. Thank you for your patience.

**Comment by cowlicks** [comment]
@ramenchef does having the extension disabled for the website work now?

This interesting, it is actually kinda a bug in citibank's code. They overwrite `String.prototype.endsWith` with `ƒ (h){return this.match(h+"$")==h}` which breaks when you pass in unmatched parentheses. However since the fingerprinting script needs to run alongside code like this, it is our responsibility to make it more robust, so I'm working on doing that now.

This bug in their code could potentially open up a XSS bug.

**Comment by ramenchef** [comment]
It seems to be working now. Thanks for the fix.
