### ISSUE TITLE
Privacy Possum causes issues for Tree Style Tab

### ISSUE THREAD

**Issue by BreadYogurt** [cowlicks/privacypossum#71]
When I enable Privacy Possum while TST is open and there is unloaded tabs, all the unloaded tabs appear to "load," however they don't really. What I mean is the tabs do an animation as if they were loading, and if CSS is applied to differentiate loaded tabs from unloaded tabs, all tabs appear loaded. However, clicking on one such tab confirms that they are not actually loaded.

Worse, though, is that upon starting up the browser with Privacy Possum enabled, Tree Style Tab takes way longer than it should to finish its initial loading. I imagine the loading time is proportionate to the number of tabs (I have Firefox set to restore my previous session upon startup). Disabling Privacy Possum fixes this issue.

I'm running Firefox Nightly v63.
Both extensions in question are at their latest versions at the time of writing.
[Link to TST on AMO.](https://addons.mozilla.org/firefox/addon/tree-style-tab/)

**Comment by cowlicks** [comment]
Hi @BreadYogurt & @RanHum sorry about the bug.

I learned that calling [`browser.webNavigation.getAllFrames`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/getAllFrames) on a TST unloaded tab causes the animation you describe. We do this on startup so that we can setup the data structure that tracks tab data.

I think the solution is to filter for [`discarded`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) aka "unloaded" tabs, then not call `getAllFrames` on them.

The problem spot is [here](https://github.com/cowlicks/privacypossum/blob/9215ce10d4203b9234012ced9db3cda6523abc69/src/js/tabs.js#L153-L162) in case anyone wants to a crack at it, before I get around to it this weekend.

cc @piroor if you get a chance, can you lmk if this sounds correct?
