### ISSUE TITLE
PP Breaks Nwetvibes/RSS Reader

### ISSUE THREAD

**Issue by Theo1352** [cowlicks/privacypossum#89]
I use Netvibes as an RSS reader, and as my homepage in Firefox 61.01. It doesn't work on any of the pages, the feeds won't render without turning off PP.

I have 100+ web sites I get feeds on, I'm not about to list them, but they won't render without turning off PP.

There also seems to be strange behavior in Netvibes, sometimes PP turns itself back on, it won't remember that action/preference.

**Comment by Theo1352** [comment]
I use Netvibes as an RSS reader, and as my homepage in Firefox 61.01. It doesn't work on any of the pages, the feeds won't render without turning off PP.

I have 100+ web sites I get feeds on, I'm not about to list them, but they won't render without turning off PP.

There also seems to be strange behavior in Netvibes, sometimes PP turns itself back on, it won't remember that action/preference.

**Comment by cowlicks** [comment]
Hello @Theo1352 thank you for the bug report. I'm able to reproduce the issue, but currently having a hard time debugging it, because of the way firefox works. I'll try to take another look at this later this week.

**Comment by Theo1352** [comment]
Cowlicks,

Thanks so much - I really like this extension a lot, but I had to remove it until there is a resolution.

I do understand the Firefox comment, indeed  - since FF60, I've had a host of problems that were never present before, I've been a user since Phoenix,  and Netscape before.

Netvibes is my home page, that's why it's so important.

Thank you and please keep me updated.

**Comment by cowlicks** [comment]
@Theo1352 I'm going to post my notes in this thread for posterity, so I can refer to them as I continue to work on this.

To debug this I'd need to be able to **start** firefox with a debug version of the extension installed. The only way to do that seems to be getting an api key from Firefox so that I can sign the extension myself, so that I can permanently install a debug version locally. So next steps are getting my own api key, or trying to reproduce this on firefox.

**Comment by cowlicks** [comment]
@Theo1352 I have code ready to fix this (see #110). I will merge it soon and make a release early next week. Thanks!

**Comment by Theo1352** [comment]
Thank you so very much...
